# This is a generated file. Not intended for manual editing.
services:
  moviemngmtsystem.api:
    build:
      context: "D:\\Programming\\repos\\MovieMngmtSystem"
      dockerfile: "MovieMngmtSystem.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/MovieMngmtSystem.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "moviemngmtsystemapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\val\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Programming\\repos\\MovieMngmtSystem\\MovieMngmtSystem.Api:/app:rw"
    - "D:\\Programming\\repos\\MovieMngmtSystem:/src:rw"
    working_dir: "/app"
