# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  moviemngmtsystem.api:
    build:
      context: "C:\\Users\\valk\\Documents\\GitHub\\MovieMngmtSystem"
      dockerfile: "MovieMngmtSystem.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/MovieMngmtSystem.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "moviemngmtsystemapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\valk\\Documents\\GitHub\\MovieMngmtSystem\\MovieMngmtSystem.Api:/app:rw"
    - "C:\\Users\\valk\\Documents\\GitHub\\MovieMngmtSystem:/src:rw"
    - "C:\\Users\\valk\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
