# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  moviemngmtsystem.api:
    build:
      context: "D:\\Programming\\repos\\MovieMngmtSystem"
      dockerfile: "MovieMngmtSystem.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "moviemngmtsystemapi:dev"
    ports:
    - "127.0.0.1:57008:57100"
    - "127.0.0.1:57208:57300"
    volumes:
    - "C:\\Users\\val\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Programming\\repos\\MovieMngmtSystem\\MovieMngmtSystem.Api:/app:rw"
    - "D:\\Programming\\repos\\MovieMngmtSystem:/src:rw"
    - "C:\\Users\\val\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\val\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\val\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_04_23_40_31:/var/opt/rider-debugger:rw"
    working_dir: "/app"
