FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./

RUN npm ci
COPY . .

RUN npm run build
FROM node:20-alpine AS production
WORKDIR /app
COPY --from=build /app/build /app/build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]